import torch
import matplotlib.pyplot as plt
from pathlib import Path
from diffusers import AutoencoderKL
import json
import os

# 1. 加载配置
with open("config.json", 'r') as f:
    cfg = json.load(f)

reflow_dir = Path(cfg['training']['reflow_data_dir'])
device = "cuda" if torch.cuda.is_available() else "cpu"

# 2. 加载 VAE
print("Loading VAE...")
vae = AutoencoderKL.from_pretrained("runwayml/stable-diffusion-v1-5", subfolder="vae").to(device)

# 3. 随便找一个 .pt 文件
pt_files = list(reflow_dir.glob("*.pt"))
if not pt_files:
    print("❌ 错误：缓存文件夹是空的！")
    exit()

print(f"🔍 发现 {len(pt_files)} 个缓存文件。正在检查第一个：{pt_files[0]}")
data = torch.load(pt_files[0], map_location=device)

x_content = data['content'].unsqueeze(0)
z_target = data['z'].unsqueeze(0)

# 4. 解码看图
def decode(latents):
    latents = latents / 0.18215
    imgs = vae.decode(latents).sample
    imgs = (imgs / 2 + 0.5).clamp(0, 1)
    return imgs.cpu().permute(0, 2, 3, 1).detach().numpy()[0]

img_c = decode(x_content)
img_z = decode(z_target)

# 5. 显示对比
plt.figure(figsize=(10, 5))
plt.subplot(1, 2, 1)
plt.title("Input (Content)")
plt.imshow(img_c)
plt.axis('off')

plt.subplot(1, 2, 2)
plt.title("Target (Generated by Stage 1)")
plt.imshow(img_z)
plt.axis('off')

plt.show()